# Generated by Django 2.2.5 on 2019-10-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190830_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.CharField(default='Categoria', max_length=12, primary_key=True, serialize=False, verbose_name='ID da Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nomeCategoria',
            field=models.CharField(max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='anoProva',
            field=models.CharField(max_length=4, verbose_name='Ano da prova'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='idProva',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID da prova'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='tipoProva',
            field=models.CharField(max_length=5, verbose_name='Tipo da prova'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='aOpcao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Letra a'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='bOpcao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Letra b'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='cOpcao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Letra c'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='dOpcao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Letra d'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='eOpcao',
            field=models.CharField(blank=True, max_length=500, verbose_name='Letra e'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='idCategoria',
            field=models.ManyToManyField(default='Categorias', to='polls.Categoria', verbose_name='ID da categoria'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='idProva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Prova', verbose_name='ID da prova'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='idQuestao',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ID da questão'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='imagem2Questao',
            field=models.FileField(blank=True, null=True, upload_to='static/img/uploads', verbose_name='Imagem 2 da questão'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='imagemQuestao',
            field=models.FileField(blank=True, null=True, upload_to='static/img/uploads', verbose_name='Imagem da questão'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='perguntaQuestao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pergunta da questão'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='respostaQuestao',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Resposta da questão'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='textoQuestao',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Texto da questão'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='idQuestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questao', verbose_name='ID da questão'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='respostaA',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resposta da letra a'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='respostaB',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resposta da letra b'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='respostaC',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resposta da letra c'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='respostaD',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resposta da letra d'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='respostaE',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Resposta da letra e'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
