# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171001_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='imagemQuestao',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/uploads'),
        ),
    ]
