# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171001_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem2Questao',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/uploads'),
        ),
    ]
