# Generated by Django 2.2.5 on 2019-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191011_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ajuda',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Ajuda da questão'),
        ),
    ]
