# Generated by Django 2.2.5 on 2019-10-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191029_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idCategoria',
        ),
    ]
