# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171001_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='aOpcao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='bOpcao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='cOpcao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='dOpcao',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='eOpcao',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
