# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171002_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('idGabarito', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('respostaGabarito', models.CharField(max_length=1)),
            ],
        ),
    ]
