# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_gabarito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gabarito',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='certaResposta',
            new_name='resposta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='matriculaUsuario',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='textoResposta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='tipoResposta',
        ),
    ]
