# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20171002_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoUsuario',
            field=models.FileField(blank=True, null=True, upload_to=b'static/img/uploads/profile'),
        ),
    ]
