# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_usuario_fotousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoQuestao',
            fields=[
                ('idTipoQuestao', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TipoQuestao', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='questao',
            name='tipoQuestao',
        ),
        migrations.AddField(
            model_name='tipoquestao',
            name='idQuestao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questao'),
        ),
    ]
