# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20171010_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoQuestao',
            new_name='AreaQuestao',
        ),
        migrations.RenameField(
            model_name='areaquestao',
            old_name='TipoQuestao',
            new_name='areaQuestao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='areaQuestao',
        ),
        migrations.AddField(
            model_name='questao',
            name='tipoQuestao',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
