# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20171010_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(default=b'Categoria', max_length=12, primary_key=True, serialize=False)),
                ('nomeCategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='idCategoria',
            field=models.ForeignKey(default=b'Categoria', on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria'),
        ),
    ]
