# Generated by Django 2.2.5 on 2019-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_usuario_idcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idCategoria',
            field=models.ManyToManyField(default='Categorias', to='polls.Categoria', verbose_name='Categoria'),
        ),
    ]
