# Generated by Django 2.2.5 on 2019-11-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_usuario_idcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='tipoProva',
            field=models.CharField(choices=[('ENADE', 'ENADE'), ('PROFMAT', 'PROFMAT')], max_length=7, verbose_name='Tipo da prova'),
        ),
    ]
